# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=2000, null=True)),
                ('number', models.IntegerField(null=True)),
                ('answer', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
