# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_user_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('answer1', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_db',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='user_db',
            name='number',
        ),
    ]
