# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20161013_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answ',
        ),
    ]
