# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_questions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='answer1',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer10',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer11',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer12',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer2',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer3',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer4',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer5',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer6',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer7',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer8',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_db',
            name='answer9',
            field=models.TextField(default='Enter Your Code Here', max_length=1000),
        ),
    ]
